version: '3'

dotenv: ['.env']

tasks:
  docker-build:
    dir: ledger-app-builder
    cmds:
      - sudo docker build -t ledger-app-builder:latest .
  docker-run:
    cmds:
      - cd {{.APP}} && sudo docker run --rm -ti -v "$(realpath .):/app" ledger-app-builder:latest
  docker-clean-app:
    cmds:
      - cd {{.APP}} && sudo docker run --rm -ti -v "$(realpath .):/app" ledger-app-builder:latest rm -rf bin debug dep obj
  docker-build-app:
    cmds:
      - cd {{.APP}} && sudo docker run --rm -ti -v "$(realpath .):/app" ledger-app-builder:latest make
  speculos-make:
    dir: speculos
    cmds:
      - cmake -Bbuild -H.
      - make -C build/
  speculos-run:
    dir: speculos
    cmds:
      - ./speculos.py ../{{.APP}}/bin/app.elf